package contributions

import "fmt"

// Contribution represents a contribution record for 2025-08-20
// Commit 7 of 20
// Generated by GreenWall
type Contribution struct {
	Date          string
	CommitNumber  int
	TotalCommits  int
}

// NewContribution creates a new contribution instance
func NewContribution() *Contribution {
	return &Contribution{
		Date:         "2025-08-20",
		CommitNumber: 7,
		TotalCommits: 20,
	}
}

// GetInfo returns the contribution information
func (c *Contribution) GetInfo() string {
	return fmt.Sprintf("Contribution on %s (%d/%d)", c.Date, c.CommitNumber, c.TotalCommits)
}

// String implements the Stringer interface
func (c *Contribution) String() string {
	return c.GetInfo()
}
